import { EventEmitter as Emitter } from 'events';
import SipMessage from './sip-parser/message';
import Response from './response';
import DrachtioAgent from './drachtio-agent';
declare class Request extends Emitter {
    msg: SipMessage;
    _res?: Response;
    _agent?: DrachtioAgent;
    source?: string;
    source_address?: string;
    source_port?: number;
    protocol?: string;
    stackTime?: string;
    stackTxnId?: string;
    stackDialogId?: string;
    server?: any;
    receivedOn?: string;
    sessionToken?: string;
    socket?: any;
    auth?: any;
    _originalParams?: any;
    canceled?: boolean;
    [key: string]: any;
    constructor(msg?: SipMessage, meta?: any);
    get res(): Response | undefined;
    set res(res: Response | undefined);
    get isNewInvite(): boolean;
    get url(): string | undefined;
    set agent(agent: DrachtioAgent | undefined);
    get agent(): DrachtioAgent | undefined;
    set meta(meta: any);
    get meta(): any;
    cancel(opts?: any, callback?: any): void;
    proxy(opts: any, callback?: any): any;
    logIn(user: any, options: any, done: any): void;
    logOut(): void;
    isAuthenticated(): boolean;
    isUnauthenticated(): boolean;
}
export default Request;
