import { EventEmitter as Emitter } from 'events';
import SipMessage from './sip-parser/message';
declare class Response extends Emitter {
    _agent?: any;
    msg: SipMessage;
    finished: boolean;
    _req?: any;
    source?: string;
    source_address?: string;
    source_port?: number;
    protocol?: string;
    stackTime?: string;
    stackTxnId?: string;
    stackDialogId?: string;
    socket?: any;
    [key: string]: any;
    constructor(agent?: any);
    get req(): any;
    set req(req: any);
    get agent(): any;
    set agent(agent: any);
    set meta(meta: any);
    get meta(): any;
    set statusCode(code: number);
    get statusCode(): number;
    get finalResponseSent(): boolean;
    get headersSent(): boolean;
    send(status: number, reason?: any, opts?: any, callback?: any, fnPrack?: any): void;
    sendAck(dialogId: string, opts?: any, callback?: any): void;
    sendPrack(dialogId: string, opts?: any, callback?: any): void;
    toJSON(): any;
    removeHeader(hdrName: string): void;
    getHeader(hdrName: string): string | undefined;
    setHeader(hdrName: string, hdrValue: any): SipMessage;
    end(data?: any, encoding?: any, callback?: any): void;
}
export = Response;
